// SKR03/SKR04-Kontenrahmen-Basisdaten (Konto, Bezeichnung, Klasse, Gruppe).
// Quelle: scka-de/german-accounting (MIT License, Dataset-Version 2026.1,
// community-kuratiert, kein offizielles DATEV-Produkt) — bei Installation
// vorbefuellt, in der App beliebig erweiterbar.

export const SKR03: [string, string, number, string | null][] = [
  ["0001", "Aufwendungen für die Ingangsetzung und Erweiterung des Geschäftsbetriebs", 0, "Immaterielle Vermögensgegenstände"],
  ["0010", "Grundstücke, grundstücksgleiche Rechte", 0, "Immaterielle Vermögensgegenstände und Sachanlagen"],
  ["0015", "Bauten auf eigenen Grundstücken", 0, "Immaterielle Vermögensgegenstände und Sachanlagen"],
  ["0027", "Gebäude auf eigenen Grundstücken", 0, "Immaterielle Vermögensgegenstände und Sachanlagen"],
  ["0030", "Grundstückseinrichtungen", 0, "Immaterielle Vermögensgegenstände und Sachanlagen"],
  ["0050", "Einbauten in fremde Grundstücke", 0, "Immaterielle Vermögensgegenstände und Sachanlagen"],
  ["0070", "Geleistete Anzahlungen auf immaterielle Vermögensgegenstände", 0, "Immaterielle Vermögensgegenstände"],
  ["0085", "Geschäfts- oder Firmenwert (entgeltlich erworben)", 0, "Immaterielle Vermögensgegenstände"],
  ["0100", "Konzessionen", 0, "Immaterielle Vermögensgegenstände"],
  ["0110", "Gewerbliche Schutzrechte", 0, "Immaterielle Vermögensgegenstände"],
  ["0115", "Ähnliche Rechte und Werte", 0, "Immaterielle Vermögensgegenstände"],
  ["0120", "Lizenzen an gewerblichen Schutzrechten", 0, "Immaterielle Vermögensgegenstände"],
  ["0135", "EDV-Software", 0, "Immaterielle Vermögensgegenstände"],
  ["0150", "Geschäfts- oder Firmenwert", 0, "Immaterielle Vermögensgegenstände"],
  ["0170", "Geleistete Anzahlungen auf immaterielle Vermögensgegenstände", 0, "Immaterielle Vermögensgegenstände"],
  ["0200", "Technische Anlagen und Maschinen", 0, "Sachanlagen"],
  ["0210", "Maschinen", 0, "Sachanlagen"],
  ["0240", "Gebäude anderer Grundstücke", 0, "Sachanlagen"],
  ["0280", "Grundstücksgleiche Rechte", 0, "Sachanlagen"],
  ["0300", "Andere Anlagen, Betriebs- und Geschäftsausstattung", 0, "Sachanlagen"],
  ["0310", "Betriebsvorrichtungen", 0, "Sachanlagen"],
  ["0320", "PKW", 0, "Sachanlagen - Fahrzeuge"],
  ["0330", "Sonstige Transportmittel", 0, "Sachanlagen - Fahrzeuge"],
  ["0340", "Sonstige Betriebs- und Geschäftsausstattung", 0, "Sachanlagen"],
  ["0350", "LKW", 0, "Sachanlagen - Fahrzeuge"],
  ["0400", "Betriebsausstattung", 0, "Sachanlagen"],
  ["0410", "Geschäftsausstattung", 0, "Sachanlagen"],
  ["0420", "Büroeinrichtung", 0, "Sachanlagen"],
  ["0440", "Ladeneinrichtung", 0, "Sachanlagen"],
  ["0450", "Einbauten in fremde Grundstücke", 0, "Sachanlagen"],
  ["0480", "Geringwertige Wirtschaftsgüter (GWG)", 0, "Sachanlagen"],
  ["0485", "Sammelposten GWG (Pool)", 0, "Sachanlagen"],
  ["0490", "Geleistete Anzahlungen und Anlagen im Bau", 0, "Sachanlagen"],
  ["0500", "Anteile an Unternehmen, mit denen ein Beteiligungsverhältnis besteht", 0, "Finanzanlagen"],
  ["0520", "Anteile an verbundenen Unternehmen", 0, "Finanzanlagen"],
  ["0540", "Wertpapiere des Anlagevermögens", 0, "Finanzanlagen"],
  ["0550", "Beteiligungen", 0, "Finanzanlagen"],
  ["0560", "Langfristige Ausleihungen an verbundene Unternehmen", 0, "Finanzanlagen"],
  ["0580", "Ausleihungen an verbundene Unternehmen", 0, "Finanzanlagen"],
  ["0600", "Sonstige Vermögensgegenstände", 0, "Sonstige Vermögensgegenstände"],
  ["0610", "Rückdeckungsansprüche aus Lebensversicherungen", 0, "Sonstige Vermögensgegenstände"],
  ["0631", "Mietkaution", 0, "Sonstige Vermögensgegenstände"],
  ["0650", "Kautionen", 0, "Sonstige Vermögensgegenstände"],
  ["0690", "Sonstige Ausleihungen", 0, "Finanzanlagen"],
  ["0700", "Pensionsrückstellungen", 0, "Rückstellungen"],
  ["0710", "Steuerrückstellungen", 0, "Rückstellungen"],
  ["0720", "Sonstige Rückstellungen", 0, "Rückstellungen"],
  ["0750", "Verbindlichkeiten gegenüber Kreditinstituten (langfristig)", 0, "Verbindlichkeiten"],
  ["0770", "Verbindlichkeiten aus Lieferungen und Leistungen (langfristig)", 0, "Verbindlichkeiten"],
  ["0790", "Sonstige Verbindlichkeiten (langfristig)", 0, "Verbindlichkeiten"],
  ["0800", "Gezeichnetes Kapital", 0, "Eigenkapital"],
  ["0810", "Gewinnvortrag", 0, "Eigenkapital"],
  ["0820", "Verlustvortrag", 0, "Eigenkapital"],
  ["0830", "Entnahmen", 0, "Eigenkapital"],
  ["0840", "Kapitalrücklage", 0, "Eigenkapital"],
  ["0850", "Privatentnahmen allgemein", 0, "Privatkonten"],
  ["0860", "Gewinnrücklage", 0, "Eigenkapital"],
  ["0880", "Gewinnvortrag vor Verwendung", 0, "Eigenkapital"],
  ["0890", "Verlustvortrag vor Verwendung", 0, "Eigenkapital"],
  ["0900", "Eigenkapital Einzelunternehmer (Festkapital)", 0, "Eigenkapital"],
  ["0920", "Privat (Entnahmen)", 0, "Privatkonten"],
  ["0930", "Privat (Steuern)", 0, "Privatkonten"],
  ["0950", "Privateinlagen", 0, "Privatkonten"],
  ["1000", "Kasse", 1, "Finanzkonten"],
  ["1010", "Nebenkasse", 1, "Finanzkonten"],
  ["1020", "Wechselkasse / Portokasse", 1, "Finanzkonten"],
  ["1100", "Postbank", 1, "Finanzkonten"],
  ["1140", "Festgeldkonto", 1, "Finanzkonten"],
  ["1200", "Bank", 1, "Finanzkonten"],
  ["1210", "Bank 2", 1, "Finanzkonten"],
  ["1300", "Wechsel", 1, "Forderungen"],
  ["1310", "Besitzwechsel", 1, "Forderungen"],
  ["1350", "Schecks", 1, "Finanzkonten"],
  ["1360", "Geldtransit", 1, "Finanzkonten"],
  ["1370", "Lohn- und Gehaltsvorschüsse", 1, "Forderungen"],
  ["1400", "Forderungen aus Lieferungen und Leistungen", 1, "Forderungen"],
  ["1406", "Forderungen aus L+L (Restlaufzeit >1J)", 1, "Forderungen"],
  ["1410", "Forderungen aus Lieferungen und Leistungen (ohne Kontokorrent)", 1, "Forderungen"],
  ["1450", "Forderungen gegen verbundene Unternehmen", 1, "Forderungen"],
  ["1460", "Forderungen gegen Gesellschafter", 1, "Forderungen"],
  ["1500", "Sonstige Vermögensgegenstände", 1, "Sonstige Vermögensgegenstände"],
  ["1510", "Forderungen gegen Personal", 1, "Sonstige Vermögensgegenstände"],
  ["1518", "Vorsteuer laufendes Jahr", 1, "Vorsteuer"],
  ["1520", "Forderungen gegen GmbH-Gesellschafter", 1, "Sonstige Vermögensgegenstände"],
  ["1540", "Geldtransit", 1, "Finanzkonten"],
  ["1545", "Verrechnungskonto Lohn und Gehalt", 1, "Sonstige Vermögensgegenstände"],
  ["1548", "Vorsteuer im Folgejahr abziehbar", 1, "Vorsteuer"],
  ["1560", "Aufzuteilende Vorsteuer", 1, "Vorsteuer"],
  ["1570", "Abziehbare Vorsteuer", 1, "Vorsteuer"],
  ["1571", "Abziehbare Vorsteuer 7%", 1, "Vorsteuer"],
  ["1576", "Abziehbare Vorsteuer 19%", 1, "Vorsteuer"],
  ["1577", "Abziehbare Vorsteuer §13b UStG", 1, "Vorsteuer"],
  ["1580", "Vorsteuer aus innergemeinschaftlichem Erwerb 19%", 1, "Vorsteuer"],
  ["1588", "Vorsteuer aus §13b UStG 19%", 1, "Vorsteuer"],
  ["1590", "Durchlaufende Posten", 1, "Sonstige Vermögensgegenstände"],
  ["1600", "Verbindlichkeiten aus Lieferungen und Leistungen", 1, "Verbindlichkeiten"],
  ["1610", "Verbindlichkeiten aus Lieferungen und Leistungen (ohne Kontokorrent)", 1, "Verbindlichkeiten"],
  ["1700", "Sonstige Verbindlichkeiten", 1, "Verbindlichkeiten"],
  ["1710", "Erhaltene Anzahlungen auf Bestellungen", 1, "Verbindlichkeiten"],
  ["1720", "Verbindlichkeiten gegen verbundene Unternehmen", 1, "Verbindlichkeiten"],
  ["1730", "Verbindlichkeiten gegenüber Kreditinstituten (kurzfristig)", 1, "Verbindlichkeiten"],
  ["1740", "Verbindlichkeiten aus Steuern und Abgaben", 1, "Verbindlichkeiten"],
  ["1741", "Verbindlichkeiten aus Lohn und Gehalt", 1, "Verbindlichkeiten"],
  ["1750", "Verbindlichkeiten im Rahmen der sozialen Sicherheit", 1, "Verbindlichkeiten"],
  ["1755", "Lohnsteuer", 1, "Verbindlichkeiten"],
  ["1756", "Solidaritätszuschlag", 1, "Verbindlichkeiten"],
  ["1757", "Kirchensteuer", 1, "Verbindlichkeiten"],
  ["1760", "Umsatzsteuervorauszahlung", 1, "Verbindlichkeiten"],
  ["1770", "Umsatzsteuer 7%", 1, "Umsatzsteuer"],
  ["1771", "Umsatzsteuer frühere Jahre", 1, "Umsatzsteuer"],
  ["1775", "Umsatzsteuer 19%", 1, "Umsatzsteuer"],
  ["1776", "Umsatzsteuer aus innergemeinschaftlichem Erwerb 19%", 1, "Umsatzsteuer"],
  ["1780", "Umsatzsteuer-Vorauszahlungen", 1, "Umsatzsteuer"],
  ["1789", "Umsatzsteuer laufendes Jahr", 1, "Umsatzsteuer"],
  ["1790", "Umsatzsteuer Vorjahr", 1, "Umsatzsteuer"],
  ["1800", "Privatentnahmen allgemein", 1, "Privatkonten"],
  ["1810", "Privatsteuern", 1, "Privatkonten"],
  ["1890", "Privateinlagen", 1, "Privatkonten"],
  ["1900", "Privatentnahmen allgemein", 1, "Privatkonten"],
  ["1910", "Privatsteuern", 1, "Privatkonten"],
  ["1920", "Sonderausgaben beschränkt abzugsfähig", 1, "Privatkonten"],
  ["1930", "Sonderausgaben unbeschränkt abzugsfähig", 1, "Privatkonten"],
  ["1940", "Zuführung Investitionsabzugsbetrag", 1, "Privatkonten"],
  ["1950", "Privateinlagen", 1, "Privatkonten"],
  ["2000", "Aufwendungen für Roh-, Hilfs- und Betriebsstoffe", 2, "Abgrenzungskonten"],
  ["2010", "Bestandsveränderungen Roh-, Hilfs- und Betriebsstoffe", 2, "Abgrenzungskonten"],
  ["2100", "Zinsen und ähnliche Aufwendungen", 2, "Abgrenzungskonten"],
  ["2110", "Zinsaufwendungen für kurzfristige Verbindlichkeiten", 2, "Abgrenzungskonten"],
  ["2120", "Zinsaufwendungen für langfristige Verbindlichkeiten", 2, "Abgrenzungskonten"],
  ["2150", "Diskontaufwendungen", 2, "Abgrenzungskonten"],
  ["2300", "Sonstige Aufwendungen für betrieblich veranlasste Abgaben", 2, "Abgrenzungskonten"],
  ["2400", "Forderungsverluste", 2, "Abgrenzungskonten"],
  ["2500", "Außerordentliche Aufwendungen", 2, "Abgrenzungskonten"],
  ["2600", "Steuern vom Einkommen und Ertrag", 2, "Abgrenzungskonten"],
  ["2650", "Körperschaftsteuer", 2, "Abgrenzungskonten"],
  ["2700", "Sonstige Zinsen und ähnliche Erträge", 2, "Abgrenzungskonten"],
  ["3000", "Roh-, Hilfs- und Betriebsstoffe", 3, "Wareneingang"],
  ["3100", "Fremdleistungen", 3, "Wareneingang"],
  ["3120", "Bauleistungen eines im Inland ansässigen Unternehmers 19% Vorsteuer und 19% Umsatzsteuer", 3, "Wareneingang"],
  ["3123", "Leistungen eines im anderen EU-Land ansässigen Unternehmens (19% VSt/19% USt)", 3, "Wareneingang"],
  ["3200", "Wareneingang", 3, "Wareneingang"],
  ["3300", "Wareneingang 7% Vorsteuer", 3, "Wareneingang"],
  ["3400", "Wareneingang 19% Vorsteuer", 3, "Wareneingang"],
  ["3425", "Innergemeinschaftlicher Erwerb 7% Vorsteuer und 7% Umsatzsteuer", 3, "Wareneingang"],
  ["3435", "Innergemeinschaftlicher Erwerb 19% Vorsteuer und 19% Umsatzsteuer", 3, "Wareneingang"],
  ["3500", "Wareneingang steuerfrei", 3, "Wareneingang"],
  ["3700", "Nachlässe aus Wareneingang", 3, "Wareneingang"],
  ["3736", "Erhaltene Skonti aus Wareneingang 19% Vorsteuer", 3, "Wareneingang"],
  ["3800", "Anschaffungsnebenkosten Wareneingang", 3, "Wareneingang"],
  ["3960", "Bestandsveränderungen fertige Erzeugnisse", 3, "Bestandsveränderungen"],
  ["4100", "Löhne", 4, "Personalaufwendungen"],
  ["4110", "Löhne für Minijobber", 4, "Personalaufwendungen"],
  ["4120", "Gehälter", 4, "Personalaufwendungen"],
  ["4125", "Geschäftsführergehälter GmbH", 4, "Personalaufwendungen"],
  ["4130", "Gesetzliche soziale Aufwendungen", 4, "Personalaufwendungen"],
  ["4138", "Beiträge zur Berufsgenossenschaft", 4, "Personalaufwendungen"],
  ["4140", "Freiwillige soziale Aufwendungen", 4, "Personalaufwendungen"],
  ["4145", "Freiwillige Krankenversicherung", 4, "Personalaufwendungen"],
  ["4150", "Vermögenswirksame Leistungen", 4, "Personalaufwendungen"],
  ["4170", "Fahrgeldzuschüsse", 4, "Personalaufwendungen"],
  ["4190", "Aushilfslöhne", 4, "Personalaufwendungen"],
  ["4199", "Lohnsteuer-Nachzahlung, pauschale Lohnsteuer", 4, "Personalaufwendungen"],
  ["4200", "Raumkosten", 4, "Raumkosten"],
  ["4210", "Miete (unbewegliche Wirtschaftsgüter)", 4, "Raumkosten"],
  ["4220", "Pacht", 4, "Raumkosten"],
  ["4230", "Heizung", 4, "Raumkosten"],
  ["4240", "Gas, Strom, Wasser", 4, "Raumkosten"],
  ["4250", "Reinigung", 4, "Raumkosten"],
  ["4260", "Instandhaltung betrieblicher Räume", 4, "Raumkosten"],
  ["4280", "Sonstige Raumkosten", 4, "Raumkosten"],
  ["4320", "Gewerbesteuer", 4, "Steuern und Versicherungen"],
  ["4360", "Versicherungen", 4, "Steuern und Versicherungen"],
  ["4380", "Beiträge", 4, "Steuern und Versicherungen"],
  ["4390", "Sonstige Abgaben", 4, "Steuern und Versicherungen"],
  ["4500", "Fahrzeugkosten", 4, "Fahrzeugkosten"],
  ["4510", "Kfz-Steuern", 4, "Fahrzeugkosten"],
  ["4520", "Kfz-Versicherungen", 4, "Fahrzeugkosten"],
  ["4530", "Laufende Kfz-Betriebskosten", 4, "Fahrzeugkosten"],
  ["4540", "Kfz-Reparaturen", 4, "Fahrzeugkosten"],
  ["4550", "Kfz-Mietleasing", 4, "Fahrzeugkosten"],
  ["4570", "Fremdfahrzeuge", 4, "Fahrzeugkosten"],
  ["4580", "Sonstige Fahrzeugkosten", 4, "Fahrzeugkosten"],
  ["4600", "Werbekosten", 4, "Werbung und Repräsentation"],
  ["4610", "Werbekosten (abziehbar)", 4, "Werbung und Repräsentation"],
  ["4630", "Geschenke abziehbar ohne §37b EStG", 4, "Werbung und Repräsentation"],
  ["4635", "Geschenke nicht abziehbar ohne §37b EStG", 4, "Werbung und Repräsentation"],
  ["4640", "Repräsentationskosten", 4, "Werbung und Repräsentation"],
  ["4650", "Bewirtungskosten", 4, "Werbung und Repräsentation"],
  ["4654", "Nicht abzugsfähige Bewirtungskosten", 4, "Werbung und Repräsentation"],
  ["4660", "Reisekosten Arbeitnehmer", 4, "Reisekosten"],
  ["4663", "Reisekosten Arbeitnehmer Fahrtkosten", 4, "Reisekosten"],
  ["4664", "Reisekosten Arbeitnehmer Verpflegung", 4, "Reisekosten"],
  ["4666", "Reisekosten Arbeitnehmer Übernachtung", 4, "Reisekosten"],
  ["4670", "Reisekosten Unternehmer", 4, "Reisekosten"],
  ["4673", "Reisekosten Unternehmer Fahrtkosten", 4, "Reisekosten"],
  ["4674", "Reisekosten Unternehmer Verpflegung", 4, "Reisekosten"],
  ["4676", "Reisekosten Unternehmer Übernachtung", 4, "Reisekosten"],
  ["4700", "Kosten der Warenabgabe", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4710", "Verpackungsmaterial", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4730", "Ausgangsfrachten", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4750", "Aufwendungen für Gewährleistungen", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4780", "Fremdarbeiten (Fremdleistungen)", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4800", "Reparaturen und Instandhaltungen", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4805", "Wartungskosten für Hard- und Software", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4806", "Wartungskosten für Software", 4, "Verschiedene betriebliche Aufwendungen"],
  ["4822", "Abschreibungen auf Sachanlagen", 4, "Abschreibungen"],
  ["4824", "Abschreibungen auf immaterielle Vermögensgegenstände", 4, "Abschreibungen"],
  ["4830", "Abschreibungen auf Sachanlagen (außerplanmäßig)", 4, "Abschreibungen"],
  ["4855", "Sofortabschreibung GWG", 4, "Abschreibungen"],
  ["4900", "Sonstige betriebliche Aufwendungen", 4, "Sonstige betriebliche Aufwendungen"],
  ["4905", "Sonstige Aufwendungen betrieblich und regelmäßig", 4, "Sonstige betriebliche Aufwendungen"],
  ["4910", "Porto", 4, "Sonstige betriebliche Aufwendungen"],
  ["4920", "Telefon", 4, "Sonstige betriebliche Aufwendungen"],
  ["4921", "Mobilfunk", 4, "Sonstige betriebliche Aufwendungen"],
  ["4925", "Internetkosten", 4, "Sonstige betriebliche Aufwendungen"],
  ["4930", "Bürobedarf", 4, "Sonstige betriebliche Aufwendungen"],
  ["4940", "Zeitschriften, Bücher", 4, "Sonstige betriebliche Aufwendungen"],
  ["4945", "Fortbildungskosten", 4, "Sonstige betriebliche Aufwendungen"],
  ["4946", "Fremdleistungen (Nicht-Wareneingang)", 4, "Sonstige betriebliche Aufwendungen"],
  ["4950", "Rechts- und Beratungskosten", 4, "Sonstige betriebliche Aufwendungen"],
  ["4955", "Buchführungskosten", 4, "Sonstige betriebliche Aufwendungen"],
  ["4957", "Abschluss- und Prüfungskosten", 4, "Sonstige betriebliche Aufwendungen"],
  ["4960", "Mieten für Einrichtungen (bewegliche Wirtschaftsgüter)", 4, "Sonstige betriebliche Aufwendungen"],
  ["4964", "Aufwendungen für die zeitlich befristete Überlassung von Rechten (Lizenzen, Konzessionen)", 4, "Sonstige betriebliche Aufwendungen"],
  ["4969", "Aufwendungen für Software (Nutzungsrechte)", 4, "Sonstige betriebliche Aufwendungen"],
  ["4970", "Nebenkosten des Geldverkehrs", 4, "Sonstige betriebliche Aufwendungen"],
  ["4980", "Werkzeuge und Kleingeräte", 4, "Sonstige betriebliche Aufwendungen"],
  ["4985", "Werkzeuge und Kleingeräte (GWG)", 4, "Sonstige betriebliche Aufwendungen"],
  ["7000", "Bestandsveränderungen fertige Erzeugnisse", 7, "Bestandsveränderungen"],
  ["7010", "Bestandsveränderungen unfertige Erzeugnisse", 7, "Bestandsveränderungen"],
  ["7020", "Bestandsveränderungen unfertige Leistungen", 7, "Bestandsveränderungen"],
  ["7080", "Andere aktivierte Eigenleistungen", 7, "Aktivierte Eigenleistungen"],
  ["7100", "Bestand fertige Erzeugnisse", 7, "Bestände"],
  ["7110", "Bestand unfertige Erzeugnisse", 7, "Bestände"],
  ["7120", "Bestand unfertige Leistungen", 7, "Bestände"],
  ["7200", "Bestand Waren", 7, "Bestände"],
  ["7300", "Erhaltene Anzahlungen auf Bestellungen", 7, "Verbindlichkeiten"],
  ["7500", "Warenbestand", 7, "Bestände"],
  ["7700", "Bestand unfertige Erzeugnisse (Bewertung)", 7, "Bestände"],
  ["7800", "Bestand fertige Erzeugnisse (Bewertung)", 7, "Bestände"],
  ["7900", "Aktivierte Eigenleistungen", 7, "Aktivierte Eigenleistungen"],
  ["8100", "Steuerfreie Umsätze §4 Nr. 1a UStG (Ausfuhrlieferungen)", 8, "Erlöse"],
  ["8110", "Steuerfreie innergemeinschaftliche Lieferungen §4 Nr.1b UStG", 8, "Erlöse"],
  ["8120", "Steuerfreie innergemeinschaftliche Lieferungen §4 Nr.1b UStG", 8, "Erlöse"],
  ["8125", "Steuerfreie ig. Lieferungen an Abnehmer mit USt-IdNr.", 8, "Erlöse"],
  ["8130", "Steuerfreie Umsätze nach §4 Nr.12 UStG (Vermietung)", 8, "Erlöse"],
  ["8135", "Steuerfreie Umsätze §4 Nr.14 ff UStG (Heilberufe)", 8, "Erlöse"],
  ["8150", "Sonstige steuerfreie Umsätze (Inland)", 8, "Erlöse"],
  ["8190", "Erlöse aus im Inland steuerpflichtigen EU-Lieferungen", 8, "Erlöse"],
  ["8200", "Erlöse", 8, "Erlöse"],
  ["8300", "Erlöse 7% USt", 8, "Erlöse"],
  ["8310", "Erlöse aus Leistungen 7% USt", 8, "Erlöse"],
  ["8320", "Erlöse Abfallverwertung", 8, "Erlöse"],
  ["8335", "Erlöse 19% USt (aus Anlagenverkäufen)", 8, "Erlöse"],
  ["8337", "Erlöse 19% USt (Sachanlagen Restbuchwert)", 8, "Erlöse"],
  ["8340", "Erlöse Provisionsumsätze", 8, "Erlöse"],
  ["8400", "Erlöse 19% USt", 8, "Erlöse"],
  ["8500", "Provisionserlöse", 8, "Erlöse"],
  ["8510", "Erlöse aus Vermietung und Verpachtung", 8, "Erlöse"],
  ["8519", "Erlöse aus Vermietung/Verpachtung 19% USt", 8, "Erlöse"],
  ["8520", "Erlöse aus Vermittlung", 8, "Erlöse"],
  ["8591", "Sachbezüge 19% USt", 8, "Erlöse"],
  ["8600", "Erlösschmälerungen", 8, "Erlöse"],
  ["8610", "Erlösschmälerungen 7% USt", 8, "Erlöse"],
  ["8620", "Erlösschmälerungen 19% USt", 8, "Erlöse"],
  ["8700", "Erlöse aus Anlagenverkäufen", 8, "Sonstige betriebliche Erträge"],
  ["8710", "Gewährte Skonti", 8, "Erlöse"],
  ["8720", "Gewährte Boni", 8, "Erlöse"],
  ["8730", "Gewährte Skonti", 8, "Erlöse"],
  ["8735", "Erlösschmälerungen 7% USt", 8, "Erlöse"],
  ["8736", "Gewährte Skonti 19% USt", 8, "Erlöse"],
  ["8740", "Gutschriften", 8, "Erlöse"],
  ["8750", "Kapitalerträge", 8, "Sonstige betriebliche Erträge"],
  ["8760", "Erträge aus Beteiligungen", 8, "Sonstige betriebliche Erträge"],
  ["8800", "Erlöse Abfallverwertung", 8, "Sonstige betriebliche Erträge"],
  ["8820", "Erträge aus der Auflösung von Rückstellungen", 8, "Sonstige betriebliche Erträge"],
  ["8900", "Private Kfz-Nutzung", 8, "Sonstige betriebliche Erträge"],
  ["8910", "Private Telefonnutzung", 8, "Sonstige betriebliche Erträge"],
  ["8920", "Verwendung von Gegenständen für Zwecke außerhalb des Unternehmens", 8, "Sonstige betriebliche Erträge"],
  ["8940", "Erträge aus Kursdifferenzen", 8, "Sonstige betriebliche Erträge"],
  ["8950", "Sonstige betriebliche Erträge", 8, "Sonstige betriebliche Erträge"],
  ["8955", "Nicht steuerbare Umsätze", 8, "Sonstige betriebliche Erträge"],
  ["8960", "Erträge aus Zuschreibungen (Sachanlagen)", 8, "Sonstige betriebliche Erträge"],
  ["8970", "Erträge aus Zuschreibungen (Finanzanlagen)", 8, "Sonstige betriebliche Erträge"],
  ["8975", "Erträge aus der Herabsetzung der Pauschalwertberichtigung", 8, "Sonstige betriebliche Erträge"],
  ["8980", "Außerordentliche Erträge", 8, "Sonstige betriebliche Erträge"],
  ["9000", "Saldenvorträge Sachkonten", 9, "Vortrags- und statistische Konten"],
  ["9008", "Saldenvorträge Debitoren", 9, "Vortrags- und statistische Konten"],
  ["9009", "Saldenvorträge Kreditoren", 9, "Vortrags- und statistische Konten"]
];

export const SKR04: [string, string, number, string | null][] = [
  ["0100", "Konzessionen", 0, "Immaterielle Vermögensgegenstände"],
  ["0110", "Gewerbliche Schutzrechte", 0, "Immaterielle Vermögensgegenstände"],
  ["0115", "Ähnliche Rechte und Werte", 0, "Immaterielle Vermögensgegenstände"],
  ["0120", "Lizenzen an gewerblichen Schutzrechten", 0, "Immaterielle Vermögensgegenstände"],
  ["0135", "EDV-Software", 0, "Immaterielle Vermögensgegenstände"],
  ["0150", "Geschäfts- oder Firmenwert (entgeltlich erworben)", 0, "Immaterielle Vermögensgegenstände"],
  ["0190", "Geleistete Anzahlungen auf immaterielle Vermögensgegenstände", 0, "Immaterielle Vermögensgegenstände"],
  ["0210", "Grundstücke, grundstücksgleiche Rechte", 0, "Sachanlagen"],
  ["0220", "Bauten auf eigenen Grundstücken", 0, "Sachanlagen"],
  ["0240", "Gebäude auf eigenen Grundstücken", 0, "Sachanlagen"],
  ["0260", "Gebäude anderer Grundstücke", 0, "Sachanlagen"],
  ["0280", "Grundstückseinrichtungen", 0, "Sachanlagen"],
  ["0290", "Einbauten in fremde Grundstücke", 0, "Sachanlagen"],
  ["0400", "Technische Anlagen und Maschinen", 0, "Sachanlagen"],
  ["0410", "Maschinen", 0, "Sachanlagen"],
  ["0500", "Andere Anlagen, Betriebs- und Geschäftsausstattung", 0, "Sachanlagen"],
  ["0510", "Betriebsvorrichtungen", 0, "Sachanlagen"],
  ["0520", "PKW", 0, "Sachanlagen"],
  ["0540", "Sonstige Transportmittel", 0, "Sachanlagen"],
  ["0550", "LKW", 0, "Sachanlagen"],
  ["0580", "Sonstige Betriebs- und Geschäftsausstattung", 0, "Sachanlagen"],
  ["0620", "Betriebsausstattung", 0, "Sachanlagen"],
  ["0630", "Geschäftsausstattung", 0, "Sachanlagen"],
  ["0640", "Büroeinrichtung", 0, "Sachanlagen"],
  ["0650", "Ladeneinrichtung", 0, "Sachanlagen"],
  ["0660", "Einbauten in fremde Grundstücke", 0, "Sachanlagen"],
  ["0670", "Geringwertige Wirtschaftsgüter (GWG)", 0, "Sachanlagen"],
  ["0675", "Sammelposten GWG (Pool)", 0, "Sachanlagen"],
  ["0690", "Geleistete Anzahlungen und Anlagen im Bau", 0, "Sachanlagen"],
  ["0700", "Anteile an verbundenen Unternehmen", 0, "Finanzanlagen"],
  ["0710", "Anteile an Unternehmen, mit denen ein Beteiligungsverhältnis besteht", 0, "Finanzanlagen"],
  ["0730", "Beteiligungen", 0, "Finanzanlagen"],
  ["0740", "Wertpapiere des Anlagevermögens", 0, "Finanzanlagen"],
  ["0750", "Langfristige Ausleihungen an verbundene Unternehmen", 0, "Finanzanlagen"],
  ["0760", "Ausleihungen an verbundene Unternehmen", 0, "Finanzanlagen"],
  ["0790", "Sonstige Ausleihungen", 0, "Finanzanlagen"],
  ["0800", "Sonstige Vermögensgegenstände", 0, "Finanzanlagen"],
  ["0810", "Rückdeckungsansprüche aus Lebensversicherungen", 0, "Finanzanlagen"],
  ["0830", "Mietkaution", 0, "Finanzanlagen"],
  ["0840", "Kautionen", 0, "Finanzanlagen"],
  ["1100", "Bestand fertige Erzeugnisse", 1, "Forderungen"],
  ["1110", "Bestand unfertige Erzeugnisse", 1, "Forderungen"],
  ["1120", "Bestand unfertige Leistungen", 1, "Forderungen"],
  ["1140", "Bestand Waren", 1, "Forderungen"],
  ["1160", "Warenbestand", 1, "Forderungen"],
  ["1200", "Forderungen aus Lieferungen und Leistungen", 1, "Forderungen"],
  ["1205", "Forderungen aus L+L (Restlaufzeit >1J)", 1, "Forderungen"],
  ["1210", "Forderungen aus Lieferungen und Leistungen (ohne Kontokorrent)", 1, "Forderungen"],
  ["1240", "Forderungen gegen verbundene Unternehmen", 1, "Forderungen"],
  ["1250", "Forderungen gegen Gesellschafter", 1, "Forderungen"],
  ["1260", "Wechsel", 1, "Forderungen"],
  ["1270", "Besitzwechsel", 1, "Forderungen"],
  ["1300", "Sonstige Vermögensgegenstände", 1, "Forderungen"],
  ["1310", "Forderungen gegen Personal", 1, "Forderungen"],
  ["1320", "Forderungen gegen GmbH-Gesellschafter", 1, "Forderungen"],
  ["1360", "Lohn- und Gehaltsvorschüsse", 1, "Forderungen"],
  ["1400", "Vorsteuer laufendes Jahr", 1, "Forderungen"],
  ["1401", "Abziehbare Vorsteuer 7%", 1, "Forderungen"],
  ["1406", "Abziehbare Vorsteuer 19%", 1, "Forderungen"],
  ["1407", "Abziehbare Vorsteuer §13b UStG", 1, "Forderungen"],
  ["1408", "Vorsteuer aus §13b UStG 19%", 1, "Forderungen"],
  ["1434", "Vorsteuer im Folgejahr abziehbar", 1, "Forderungen"],
  ["1440", "Schecks", 1, "Forderungen"],
  ["1450", "Aufzuteilende Vorsteuer", 1, "Forderungen"],
  ["1460", "Geldtransit", 1, "Forderungen"],
  ["1490", "Durchlaufende Posten", 1, "Forderungen"],
  ["1600", "Kasse", 1, "Liquide Mittel"],
  ["1610", "Nebenkasse", 1, "Liquide Mittel"],
  ["1620", "Wechselkasse / Portokasse", 1, "Liquide Mittel"],
  ["1700", "Postbank", 1, "Liquide Mittel"],
  ["1740", "Festgeldkonto", 1, "Liquide Mittel"],
  ["1800", "Bank", 1, "Sonstige Vermögensgegenstände"],
  ["1810", "Bank 2", 1, "Sonstige Vermögensgegenstände"],
  ["2000", "Eigenkapital Einzelunternehmer (Festkapital)", 2, "Eigenkapital"],
  ["2100", "Entnahmen", 2, "Eigenkapital"],
  ["2150", "Privat (Steuern)", 2, "Eigenkapital"],
  ["2180", "Privateinlagen", 2, "Eigenkapital"],
  ["2200", "Sonderausgaben beschränkt abzugsfähig", 2, "Eigenkapital"],
  ["2300", "Sonderausgaben unbeschränkt abzugsfähig", 2, "Eigenkapital"],
  ["2900", "Gezeichnetes Kapital", 2, "Privatkonten"],
  ["2920", "Kapitalrücklage", 2, "Privatkonten"],
  ["2950", "Gewinnrücklage", 2, "Privatkonten"],
  ["2960", "Gewinnvortrag", 2, "Privatkonten"],
  ["2970", "Gewinnvortrag vor Verwendung", 2, "Privatkonten"],
  ["2978", "Verlustvortrag", 2, "Privatkonten"],
  ["3030", "Steuerrückstellungen", 3, "Rückstellungen"],
  ["3070", "Pensionsrückstellungen", 3, "Rückstellungen"],
  ["3090", "Sonstige Rückstellungen", 3, "Rückstellungen"],
  ["3150", "Verbindlichkeiten gegenüber Kreditinstituten (langfristig)", 3, "Verbindlichkeiten"],
  ["3260", "Erhaltene Anzahlungen auf Bestellungen", 3, "Verbindlichkeiten"],
  ["3300", "Verbindlichkeiten aus Lieferungen und Leistungen (langfristig)", 3, "Verbindlichkeiten"],
  ["3310", "Verbindlichkeiten aus Lieferungen und Leistungen (ohne Kontokorrent)", 3, "Verbindlichkeiten"],
  ["3400", "Verbindlichkeiten gegen verbundene Unternehmen", 3, "Verbindlichkeiten"],
  ["3500", "Sonstige Verbindlichkeiten (langfristig)", 3, "Verbindlichkeiten"],
  ["3520", "Verbindlichkeiten aus Steuern und Abgaben", 3, "Verbindlichkeiten"],
  ["3720", "Verbindlichkeiten aus Lohn und Gehalt", 3, "Verbindlichkeiten"],
  ["3730", "Lohnsteuer", 3, "Verbindlichkeiten"],
  ["3731", "Solidaritätszuschlag", 3, "Verbindlichkeiten"],
  ["3732", "Kirchensteuer", 3, "Verbindlichkeiten"],
  ["3740", "Verbindlichkeiten im Rahmen der sozialen Sicherheit", 3, "Verbindlichkeiten"],
  ["3800", "Umsatzsteuer", 3, "Umsatzsteuer"],
  ["3801", "Umsatzsteuer 7%", 3, "Umsatzsteuer"],
  ["3806", "Umsatzsteuer 19%", 3, "Umsatzsteuer"],
  ["3807", "Umsatzsteuer aus innergemeinschaftlichem Erwerb 19%", 3, "Umsatzsteuer"],
  ["3820", "Umsatzsteuervorauszahlung", 3, "Umsatzsteuer"],
  ["3841", "Umsatzsteuer laufendes Jahr", 3, "Umsatzsteuer"],
  ["3845", "Umsatzsteuer frühere Jahre", 3, "Umsatzsteuer"],
  ["4100", "Steuerfreie Umsätze §4 Nr. 1a UStG (Ausfuhrlieferungen)", 4, "Erlöse"],
  ["4120", "Steuerfreie innergemeinschaftliche Lieferungen §4 Nr.1b UStG", 4, "Erlöse"],
  ["4125", "Steuerfreie innergemeinschaftliche Lieferungen §4 Nr.1b UStG", 4, "Erlöse"],
  ["4130", "Steuerfreie ig. Lieferungen an Abnehmer mit USt-IdNr.", 4, "Erlöse"],
  ["4140", "Steuerfreie Umsätze nach §4 Nr.12 UStG (Vermietung)", 4, "Erlöse"],
  ["4145", "Steuerfreie Umsätze §4 Nr.14 ff UStG (Heilberufe)", 4, "Erlöse"],
  ["4150", "Sonstige steuerfreie Umsätze (Inland)", 4, "Erlöse"],
  ["4190", "Erlöse aus im Inland steuerpflichtigen EU-Lieferungen", 4, "Erlöse"],
  ["4200", "Erlöse", 4, "Erlöse"],
  ["4300", "Erlöse 7% USt", 4, "Erlöse"],
  ["4310", "Erlöse aus Leistungen 7% USt", 4, "Erlöse"],
  ["4320", "Erlöse Abfallverwertung", 4, "Erlöse"],
  ["4335", "Erlöse 19% USt (aus Anlagenverkäufen)", 4, "Erlöse"],
  ["4337", "Erlöse 19% USt (Sachanlagen Restbuchwert)", 4, "Erlöse"],
  ["4340", "Erlöse Provisionsumsätze", 4, "Erlöse"],
  ["4400", "Erlöse 19% USt", 4, "Erlöse"],
  ["4500", "Provisionserlöse", 4, "Erlöse"],
  ["4510", "Erlöse aus Vermietung und Verpachtung", 4, "Erlöse"],
  ["4519", "Erlöse aus Vermietung/Verpachtung 19% USt", 4, "Erlöse"],
  ["4520", "Erlöse aus Vermittlung", 4, "Erlöse"],
  ["4590", "Sachbezüge 19% USt", 4, "Erlöse"],
  ["4600", "Erlösschmälerungen", 4, "Erlöse"],
  ["4610", "Erlösschmälerungen 7% USt", 4, "Erlöse"],
  ["4620", "Erlösschmälerungen 19% USt", 4, "Erlöse"],
  ["4710", "Gewährte Skonti", 4, "Erlöse"],
  ["4720", "Gewährte Boni", 4, "Erlöse"],
  ["4730", "Gewährte Skonti", 4, "Erlöse"],
  ["4735", "Erlösschmälerungen 7% USt", 4, "Erlöse"],
  ["4736", "Gewährte Skonti 19% USt", 4, "Erlöse"],
  ["4740", "Gutschriften", 4, "Erlöse"],
  ["4750", "Kapitalerträge", 4, "Erlöse"],
  ["4760", "Erträge aus Beteiligungen", 4, "Erlöse"],
  ["4820", "Erträge aus der Auflösung von Rückstellungen", 4, "Erlöse"],
  ["4830", "Erlöse Abfallverwertung", 4, "Erlöse"],
  ["4840", "Erträge aus Kursdifferenzen", 4, "Erlöse"],
  ["4845", "Erlöse aus Anlagenverkäufen", 4, "Erlöse"],
  ["4900", "Private Kfz-Nutzung", 4, "Erlöse"],
  ["4910", "Private Telefonnutzung", 4, "Erlöse"],
  ["4920", "Verwendung von Gegenständen für Zwecke außerhalb des Unternehmens", 4, "Erlöse"],
  ["4950", "Sonstige betriebliche Erträge", 4, "Erlöse"],
  ["4955", "Nicht steuerbare Umsätze", 4, "Erlöse"],
  ["4960", "Erträge aus Zuschreibungen (Sachanlagen)", 4, "Erlöse"],
  ["4970", "Erträge aus Zuschreibungen (Finanzanlagen)", 4, "Erlöse"],
  ["4975", "Erträge aus der Herabsetzung der Pauschalwertberichtigung", 4, "Erlöse"],
  ["4980", "Außerordentliche Erträge", 4, "Erlöse"],
  ["5000", "Aufwendungen für Roh-, Hilfs- und Betriebsstoffe", 5, "Materialaufwand und Wareneinsatz"],
  ["5020", "Bestandsveränderungen Roh-, Hilfs- und Betriebsstoffe", 5, "Materialaufwand und Wareneinsatz"],
  ["5200", "Wareneingang", 5, "Materialaufwand und Wareneinsatz"],
  ["5300", "Wareneingang 7% Vorsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5400", "Wareneingang 19% Vorsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5425", "Innergemeinschaftlicher Erwerb 7% Vorsteuer und 7% Umsatzsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5435", "Innergemeinschaftlicher Erwerb 19% Vorsteuer und 19% Umsatzsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5500", "Wareneingang steuerfrei", 5, "Materialaufwand und Wareneinsatz"],
  ["5700", "Nachlässe aus Wareneingang", 5, "Materialaufwand und Wareneinsatz"],
  ["5736", "Erhaltene Skonti aus Wareneingang 19% Vorsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5800", "Anschaffungsnebenkosten Wareneingang", 5, "Materialaufwand und Wareneinsatz"],
  ["5810", "Bestandsveränderungen unfertige Erzeugnisse", 5, "Materialaufwand und Wareneinsatz"],
  ["5820", "Bestandsveränderungen unfertige Leistungen", 5, "Materialaufwand und Wareneinsatz"],
  ["5880", "Andere aktivierte Eigenleistungen", 5, "Materialaufwand und Wareneinsatz"],
  ["5900", "Fremdleistungen", 5, "Materialaufwand und Wareneinsatz"],
  ["5920", "Bauleistungen eines im Inland ansässigen Unternehmers 19% Vorsteuer und 19% Umsatzsteuer", 5, "Materialaufwand und Wareneinsatz"],
  ["5923", "Leistungen eines im anderen EU-Land ansässigen Unternehmens (19% VSt/19% USt)", 5, "Materialaufwand und Wareneinsatz"],
  ["5960", "Bestandsveränderungen fertige Erzeugnisse", 5, "Materialaufwand und Wareneinsatz"],
  ["6000", "Löhne", 6, "Betriebliche Aufwendungen"],
  ["6010", "Löhne für Minijobber", 6, "Betriebliche Aufwendungen"],
  ["6020", "Gehälter", 6, "Betriebliche Aufwendungen"],
  ["6024", "Geschäftsführergehälter GmbH", 6, "Betriebliche Aufwendungen"],
  ["6050", "Aushilfslöhne", 6, "Betriebliche Aufwendungen"],
  ["6060", "Fahrgeldzuschüsse", 6, "Betriebliche Aufwendungen"],
  ["6070", "Lohnsteuer-Nachzahlung, pauschale Lohnsteuer", 6, "Betriebliche Aufwendungen"],
  ["6110", "Gesetzliche soziale Aufwendungen", 6, "Betriebliche Aufwendungen"],
  ["6120", "Beiträge zur Berufsgenossenschaft", 6, "Betriebliche Aufwendungen"],
  ["6130", "Freiwillige soziale Aufwendungen", 6, "Betriebliche Aufwendungen"],
  ["6140", "Freiwillige Krankenversicherung", 6, "Betriebliche Aufwendungen"],
  ["6150", "Vermögenswirksame Leistungen", 6, "Betriebliche Aufwendungen"],
  ["6200", "Abschreibungen auf immaterielle Vermögensgegenstände", 6, "Betriebliche Aufwendungen"],
  ["6220", "Abschreibungen auf Sachanlagen", 6, "Betriebliche Aufwendungen"],
  ["6230", "Abschreibungen auf Sachanlagen (außerplanmäßig)", 6, "Betriebliche Aufwendungen"],
  ["6260", "Sofortabschreibung GWG", 6, "Betriebliche Aufwendungen"],
  ["6300", "Raumkosten", 6, "Betriebliche Aufwendungen"],
  ["6305", "Sonstige Aufwendungen betrieblich und regelmäßig", 6, "Betriebliche Aufwendungen"],
  ["6310", "Miete (unbewegliche Wirtschaftsgüter)", 6, "Betriebliche Aufwendungen"],
  ["6315", "Pacht", 6, "Betriebliche Aufwendungen"],
  ["6325", "Heizung", 6, "Betriebliche Aufwendungen"],
  ["6330", "Gas, Strom, Wasser", 6, "Betriebliche Aufwendungen"],
  ["6335", "Reinigung", 6, "Betriebliche Aufwendungen"],
  ["6340", "Instandhaltung betrieblicher Räume", 6, "Betriebliche Aufwendungen"],
  ["6345", "Sonstige Raumkosten", 6, "Betriebliche Aufwendungen"],
  ["6400", "Versicherungen", 6, "Betriebliche Aufwendungen"],
  ["6420", "Beiträge", 6, "Betriebliche Aufwendungen"],
  ["6430", "Sonstige Abgaben", 6, "Betriebliche Aufwendungen"],
  ["6460", "Reparaturen und Instandhaltungen", 6, "Betriebliche Aufwendungen"],
  ["6475", "Wartungskosten für Hard- und Software", 6, "Betriebliche Aufwendungen"],
  ["6476", "Wartungskosten für Software", 6, "Betriebliche Aufwendungen"],
  ["6500", "Fahrzeugkosten", 6, "Betriebliche Aufwendungen"],
  ["6520", "Kfz-Steuern", 6, "Betriebliche Aufwendungen"],
  ["6530", "Laufende Kfz-Betriebskosten", 6, "Betriebliche Aufwendungen"],
  ["6540", "Kfz-Versicherungen", 6, "Betriebliche Aufwendungen"],
  ["6545", "Kfz-Reparaturen", 6, "Betriebliche Aufwendungen"],
  ["6550", "Kfz-Mietleasing", 6, "Betriebliche Aufwendungen"],
  ["6570", "Fremdfahrzeuge", 6, "Betriebliche Aufwendungen"],
  ["6580", "Sonstige Fahrzeugkosten", 6, "Betriebliche Aufwendungen"],
  ["6600", "Werbekosten", 6, "Betriebliche Aufwendungen"],
  ["6610", "Werbekosten (abziehbar)", 6, "Betriebliche Aufwendungen"],
  ["6620", "Geschenke abziehbar ohne §37b EStG", 6, "Betriebliche Aufwendungen"],
  ["6625", "Geschenke nicht abziehbar ohne §37b EStG", 6, "Betriebliche Aufwendungen"],
  ["6630", "Repräsentationskosten", 6, "Betriebliche Aufwendungen"],
  ["6640", "Bewirtungskosten", 6, "Betriebliche Aufwendungen"],
  ["6644", "Nicht abzugsfähige Bewirtungskosten", 6, "Betriebliche Aufwendungen"],
  ["6650", "Reisekosten Arbeitnehmer", 6, "Betriebliche Aufwendungen"],
  ["6660", "Reisekosten Arbeitnehmer Fahrtkosten", 6, "Betriebliche Aufwendungen"],
  ["6664", "Reisekosten Arbeitnehmer Verpflegung", 6, "Betriebliche Aufwendungen"],
  ["6668", "Reisekosten Arbeitnehmer Übernachtung", 6, "Betriebliche Aufwendungen"],
  ["6670", "Reisekosten Unternehmer", 6, "Betriebliche Aufwendungen"],
  ["6673", "Reisekosten Unternehmer Fahrtkosten", 6, "Betriebliche Aufwendungen"],
  ["6674", "Reisekosten Unternehmer Verpflegung", 6, "Betriebliche Aufwendungen"],
  ["6680", "Reisekosten Unternehmer Übernachtung", 6, "Betriebliche Aufwendungen"],
  ["6700", "Kosten der Warenabgabe", 6, "Betriebliche Aufwendungen"],
  ["6730", "Ausgangsfrachten", 6, "Betriebliche Aufwendungen"],
  ["6740", "Verpackungsmaterial", 6, "Betriebliche Aufwendungen"],
  ["6780", "Aufwendungen für Gewährleistungen", 6, "Betriebliche Aufwendungen"],
  ["6800", "Porto", 6, "Betriebliche Aufwendungen"],
  ["6805", "Telefon", 6, "Betriebliche Aufwendungen"],
  ["6810", "Mobilfunk", 6, "Betriebliche Aufwendungen"],
  ["6815", "Internetkosten", 6, "Betriebliche Aufwendungen"],
  ["6820", "Bürobedarf", 6, "Betriebliche Aufwendungen"],
  ["6825", "Zeitschriften, Bücher", 6, "Betriebliche Aufwendungen"],
  ["6827", "Abschluss- und Prüfungskosten", 6, "Betriebliche Aufwendungen"],
  ["6830", "Fortbildungskosten", 6, "Betriebliche Aufwendungen"],
  ["6835", "Fremdleistungen (Nicht-Wareneingang)", 6, "Betriebliche Aufwendungen"],
  ["6837", "Aufwendungen für die zeitlich befristete Überlassung von Rechten (Lizenzen, Konzessionen)", 6, "Betriebliche Aufwendungen"],
  ["6838", "Aufwendungen für Software (Nutzungsrechte)", 6, "Betriebliche Aufwendungen"],
  ["6845", "Werkzeuge und Kleingeräte", 6, "Betriebliche Aufwendungen"],
  ["6855", "Nebenkosten des Geldverkehrs", 6, "Betriebliche Aufwendungen"],
  ["6930", "Forderungsverluste", 6, "Betriebliche Aufwendungen"],
  ["7100", "Sonstige Zinsen und ähnliche Erträge", 7, "Weitere Erträge und Aufwendungen"],
  ["7300", "Zinsen und ähnliche Aufwendungen", 7, "Weitere Erträge und Aufwendungen"],
  ["7310", "Zinsaufwendungen für kurzfristige Verbindlichkeiten", 7, "Weitere Erträge und Aufwendungen"],
  ["7320", "Zinsaufwendungen für langfristige Verbindlichkeiten", 7, "Weitere Erträge und Aufwendungen"],
  ["7330", "Diskontaufwendungen", 7, "Weitere Erträge und Aufwendungen"],
  ["7500", "Außerordentliche Aufwendungen", 7, "Weitere Erträge und Aufwendungen"],
  ["7600", "Steuern vom Einkommen und Ertrag", 7, "Weitere Erträge und Aufwendungen"],
  ["7610", "Körperschaftsteuer", 7, "Weitere Erträge und Aufwendungen"],
  ["7680", "Sonstige Aufwendungen für betrieblich veranlasste Abgaben", 7, "Weitere Erträge und Aufwendungen"],
  ["9000", "Saldenvorträge Sachkonten", 9, "Vortrags- und statistische Konten"],
  ["9008", "Saldenvorträge Debitoren", 9, "Vortrags- und statistische Konten"],
  ["9009", "Saldenvorträge Kreditoren", 9, "Vortrags- und statistische Konten"]
];
